name: 'Build Corne'
on:
  workflow_dispatch:
  push:
    paths:
      - 'config/includes/*'
      - 'config/corne.*'
      - '.github/workflows/build_corne.yml'

jobs:
  build_black:
    # https://github.com/zmkfirmware/zmk/blob/main/.github/workflows/build-user-config.yml
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3.0
    with:
      build_matrix_path: build_corne.yaml            # default: "build.yaml"
